.\" etc. to Steve Cheng <steve@ggi-project.org>.
.TH "PWOL" "1" "13 May 2017" "" ""

.SH NAME
pwol \- Send Wake-On-LAN (WoL) packets to wake-up hosts over the network

.SH SYNOPSIS
pwol [ options] [<host|group-1> [... <host|group-N>]]

.SH "DESCRIPTION"
.PP
pwol is a tool that can be used to send WoL (Wake-On-LAN 
network packets in order to wake-up sleeping hosts.
.PP
More information and new relaseses may be found at the following website:
http://https://github.com/ptrrkssn/pwol
.SH "OPTIONS"
.TP
-h
Show summary of options.
.TP
-v
Increase verbosity level.
.TP
-V
Print build version.
.TP
-i
Ignore errors.
.TP
-n
No-send mode.
.TP
-D
Dump configuration.
.TP
-d
Increase internal debugging level.
.TP
-f <path>
Load additional configuration files.
.TP
-g <name>
Force (override) gateway.
.TP
-a <address>
Force (override) gateway address (DNS name).
.TP
-p <service>
Force (override) gateway port (service name).
.TP
-s <delay>
Force (override) inter-packet delay.
.TP
-c <count>
Force (override) packet copies for hosts/groups.
.TP
-S <secret>
Force (override) WoL secret.
.SH "DETAILS"
Bla bla bla
.SH "SEE ALSO"
.PP
ping (8)
.SH "AUTHOR"
.PP
pwol was written by Peter Eriksson <pen@lysator.liu.se>.
.PP
.SH "LICENSE"
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
.PP
* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.
.PP
* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.
.PP
* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.
.PP
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
