# $FreeBSD$

PORTNAME=		pwol
DISTVERSIONPREFIX=	v
DISTVERSION=		1.5
CATEGORIES=		sysutils

MAINTAINER=		pen@lysator.liu.se
COMMENT=		Peter's Wake-on-LAN Tool

LICENSE=		BSD3CLAUSE
LICENSE_FILE=		${WRKSRC}/LICENSE

USE_GITHUB=		yes
GH_ACCOUNT=		ptrrkssn

GNU_CONFIGURE=		yes

PLIST_FILES=		bin/pwol \
			man/man1/pwol.1.gz \
			man/man5/pwol.conf.5.gz \
			etc/pwol.conf.sample

.include <bsd.port.mk>
